apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/betosales/kind-kong.git
    targetRevision: HEAD
    path: apps/konga
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: kong
          hosts:
          - konga.local
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
