apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pantsel/konga.git
    targetRevision: "0.14.19"
    chart: konga

  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
